//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Crud_Angular.Models
{
    
    
    public partial class Pessoas
    {
        public int Id { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public string email { get; set; }
        public string telefones { get; set; }
    
        public virtual Telefone Telefone { get; set; }
    }
}
