//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Crud_Angular.Models
{
    
    public partial class Telefone
    {
        public int Id { get; set; }
        public string ddd { get; set; }
        public string numero { get; set; }
    
        public virtual Pessoas Pessoa { get; set; }
    }
}
